# Generated by Django 5.1.4 on 2026-06-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile_gc_userprofile_gc_ceiling_userprofile_gf_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effect_id",
                    models.CharField(
                        help_text="Уникальный идентификатор типа: blueprint_effect, iron_fast_effect...",
                        max_length=80,
                        verbose_name="ID эффекта",
                    ),
                ),
                (
                    "skill_id",
                    models.CharField(
                        help_text="blueprint, system_overload, iron_fast...",
                        max_length=50,
                        verbose_name="ID скилла",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Данные эффекта")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда эффект перестаёт действовать. null = пока не потреблён.",
                        null=True,
                        verbose_name="Истекает",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_effects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Активный эффект",
                "verbose_name_plural": "Активные эффекты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillCooldown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_id", models.CharField(max_length=50, verbose_name="ID скилла")),
                ("cooldown_until", models.DateTimeField(verbose_name="Кулдаун до")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_cooldowns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кулдаун скилла",
                "verbose_name_plural": "Кулдауны скиллов",
                "unique_together": {("user", "skill_id")},
            },
        ),
    ]
