# Generated by Django 5.1.4 on 2026-06-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_bossencounter_reward_multiplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="damage_multiplier",
            field=models.FloatField(default=1.0, verbose_name="Множитель урона"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gold_multiplier",
            field=models.FloatField(default=1.0, verbose_name="Множитель золота"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="xp_multiplier",
            field=models.FloatField(default=1.0, verbose_name="Множитель опыта"),
        ),
    ]
