# Generated by Django 6.0.6 on 2026-06-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_userprofile_damage_multiplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rank_xp",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Опыт ранга (Rank XP)"
            ),
        ),
    ]
