# Generated by Django 6.0.6 on 2026-06-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_userprofile_rank_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_daily_cron_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Последний крон дейликов"
            ),
        ),
    ]
