# Generated by Django 6.0.6 on 2026-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_userprofile_last_daily_cron_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="neg_streak",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Отрицательный стрик привычки"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="pos_streak",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Положительный стрик привычки"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="streak",
            field=models.PositiveIntegerField(default=0, verbose_name="Стрик дейлика"),
        ),
    ]
