# Generated by Django 5.1.4 on 2026-06-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_task_neg_streak_task_pos_streak_task_streak"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Уникальный код (напр. misted_hood)",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("equipment", "Equipment"),
                            ("consumable", "Consumable"),
                            ("material", "Material"),
                        ],
                        default="equipment",
                        max_length=20,
                    ),
                ),
                (
                    "damage_boost",
                    models.FloatField(default=0.0, verbose_name="Множитель урона (+%)"),
                ),
                (
                    "gold_boost",
                    models.FloatField(
                        default=0.0, verbose_name="Множитель золота (+%)"
                    ),
                ),
                (
                    "xp_boost",
                    models.FloatField(default=0.0, verbose_name="Множитель опыта (+%)"),
                ),
                (
                    "hp_boost",
                    models.IntegerField(default=0, verbose_name="Бонус к HP (Flat)"),
                ),
                (
                    "mana_boost",
                    models.IntegerField(default=0, verbose_name="Бонус к Мане (Flat)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effect_name",
                    models.CharField(max_length=100, verbose_name="Название эффекта"),
                ),
                (
                    "effect_value",
                    models.FloatField(default=0.0, verbose_name="Значение эффекта"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="api.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "is_equipped",
                    models.BooleanField(default=False, verbose_name="Экипировано"),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="api.userprofile",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.item"
                    ),
                ),
            ],
            options={
                "unique_together": {("user_profile", "item")},
            },
        ),
    ]
