# Generated by Django 5.1.4 on 2026-06-28 13:31

from django.db import migrations


def migrate_data(apps, schema_editor):
    UserProfile = apps.get_model("api", "UserProfile")
    Item = apps.get_model("api", "Item")
    InventoryItem = apps.get_model("api", "InventoryItem")

    # Seed known items first
    known_items = {
        "misted_hood": {"name": "Misted Wanderer's Hood", "hp_boost": 20},
        "bone_bracelet": {"name": "Bone Bracelet", "damage_boost": 0.05},
        "heralds_fang": {"name": "Herald's Fang", "damage_boost": 0.10},
        "wardens_quill": {"name": "Warden's Quill", "xp_boost": 0.05},
        "echo_bell": {"name": "Echo Bell", "gold_boost": 0.10},
        "frostbite_blade": {"name": "Frostbite Blade", "damage_boost": 0.15},
        "silk_mantle": {"name": "Silk Mantle", "hp_boost": 50},
    }

    # Ensure items exist
    for code, data in known_items.items():
        Item.objects.get_or_create(code=code, defaults=data)

    for profile in UserProfile.objects.all():
        inventory = profile.inventory if isinstance(profile.inventory, list) else []
        equipped = profile.equipped if isinstance(profile.equipped, dict) else {}

        # Process inventory items
        item_counts = {}
        for item_data in inventory:
            item_id = item_data.get("id")
            if item_id:
                item_counts[item_id] = item_counts.get(item_id, 0) + 1

        for item_id, count in item_counts.items():
            # If the item doesn't exist, create a dummy one
            item, _ = Item.objects.get_or_create(
                code=item_id, defaults={"name": f"Unknown Item ({item_id})"}
            )

            # Check if it's equipped in any slot
            is_equipped = False
            for slot, equipped_item in equipped.items():
                if equipped_item and equipped_item.get("id") == item_id:
                    is_equipped = True
                    break

            InventoryItem.objects.create(
                user_profile=profile, item=item, quantity=count, is_equipped=is_equipped
            )


def reverse_migrate(apps, schema_editor):
    InventoryItem = apps.get_model("api", "InventoryItem")
    InventoryItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_item_itemeffect_inventoryitem"),
    ]

    operations = [migrations.RunPython(migrate_data, reverse_migrate)]
