# Generated by Django 5.1.4 on 2026-06-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_migrate_json_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="equipped",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="inventory",
        ),
    ]
