# Generated by Django 5.1.4 on 2026-06-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_item_cost_recipe_recipeingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="icon_url",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="URL иконки (WEBP)"
            ),
        ),
    ]
