# Generated by Django 6.0.6 on 2026-06-29 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_userprofile_last_training_at_recruitedally_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks_completed', models.PositiveIntegerField(default=0)),
                ('max_streak', models.PositiveIntegerField(default=0)),
                ('total_boss_damage', models.PositiveIntegerField(default=0)),
                ('bosses_defeated', models.PositiveIntegerField(default=0)),
                ('total_gold_earned', models.PositiveIntegerField(default=0)),
                ('prayer_sessions', models.PositiveIntegerField(default=0)),
                ('total_crits', models.PositiveIntegerField(default=0)),
                ('allies_recruited', models.PositiveIntegerField(default=0)),
                ('ally_max_level', models.PositiveIntegerField(default=0)),
                ('unique_subjects', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.CharField(max_length=100)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'unique_together': {('user', 'achievement_id')},
            },
        ),
    ]
