# Generated by Django 5.1.4 on 2026-06-29 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userstats_highest_subject_rank_userstats_prayer_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'task_type'], name='api_task_user_id_a0ed02_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'is_completed'], name='api_task_user_id_ad64e3_idx'),
        ),
    ]
