# Generated by Django 6.0.6 on 2026-06-30 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_task_boss_damage_task_category_task_default_focus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_key', models.CharField(max_length=100, verbose_name='Активность')),
                ('hours', models.FloatField(default=0, verbose_name='Часы')),
                ('focus_rating', models.FloatField(default=5, verbose_name='Фокус')),
                ('efficiency', models.FloatField(default=1.0, verbose_name='Эффективность')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='Полученный опыт')),
                ('gf_gain', models.FloatField(default=0, verbose_name='Gf Gain')),
                ('gc_gain', models.FloatField(default=0, verbose_name='Gc Gain')),
                ('ps_gain', models.FloatField(default=0, verbose_name='Ps Gain')),
                ('vm_gain', models.FloatField(default=0, verbose_name='Vm Gain')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сессии')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='api.userprofile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Тренировочная сессия',
                'verbose_name_plural': 'Тренировочные сессии',
                'ordering': ['-created_at'],
            },
        ),
    ]
