# Generated by Django 5.1.4 on 2026-07-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_task_xp_awarded_gold_awarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hp_max',
        ),
    ]
