# Generated by Django 5.1.4 on 2026-07-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_remove_userprofile_hp_max"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="active_mutators",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Активные мутаторы"
            ),
        ),
    ]
