# Generated by Django 5.1.4 on 2026-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_userprofile_active_mutators"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rival_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Данные соперника"
            ),
        ),
    ]
