# Generated by Django 5.1.4 on 2026-07-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_userprofile_rival_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_daily_cron_at",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Последнее ежедневное обновление (Mutators)",
            ),
        ),
    ]
