# Generated by Django 5.1.4 on 2026-07-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_userprofile_last_daily_cron_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="streak",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Стрик (дней подряд)"
            ),
        ),
    ]
