# Generated by Django 5.1.4 on 2026-07-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_userprofile_streak"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="stat_bonuses",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Уникальные характеристики"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="boss_rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "E"),
                    ("D", "D"),
                    ("C", "C"),
                    ("B", "B"),
                    ("A", "A"),
                    ("S", "S"),
                    ("SS", "SS"),
                    ("SSS", "SSS"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_purchasable",
            field=models.BooleanField(default=True, verbose_name="Доступен в магазине"),
        ),
        migrations.AddField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("shop", "Shop"),
                    ("boss_drop", "Boss Drop"),
                    ("quest_reward", "Quest Reward"),
                ],
                default="shop",
                max_length=20,
            ),
        ),
    ]
