# Generated by Django 5.1.4 on 2026-07-01 20:24

from django.db import migrations
import random


def backfill_boss_drops(apps, schema_editor):
    Item = apps.get_model("api", "Item")
    Boss = apps.get_model("api", "Boss")
    InventoryItem = apps.get_model("api", "InventoryItem")

    RANK_TO_LEVEL = {
        1: "F",
        2: "D",
        3: "C",
        4: "B",
        5: "A",
        6: "S",
        7: "SS",
        8: "SSS",
    }

    BOSS_RANK_STATS = {
        "F": {"count": 1, "min": 1, "max": 1},
        "D": {"count": 1, "min": 1, "max": 2},
        "C": {"count": 2, "min": 2, "max": 2},
        "B": {"count": 2, "min": 2, "max": 3},
        "A": {"count": 3, "min": 3, "max": 3},
        "S": {"count": 3, "min": 3, "max": 4},
        "SS": {"count": 4, "min": 4, "max": 4},
        "SSS": {"count": 4, "min": 4, "max": 5},
    }
    POSSIBLE_STATS = ["pwr", "def", "foc", "mem", "spd", "lck"]

    # NOTE: This migration is a historical one-time backfill.
    # Going forward, the single source of truth for re-syncing Boss Drop
    # flags and stats is the management command `sync_boss_drops`
    # (run via `python manage.py sync_boss_drops`).

    # We iterate all bosses and backfill the corresponding Items
    for boss in Boss.objects.all():
        if not boss.drop_item_id:
            continue

        try:
            item = Item.objects.get(code=boss.drop_item_id)
            item.is_purchasable = False
            item.source = "boss_drop"
            rank = RANK_TO_LEVEL.get(boss.level, "F")
            item.boss_rank = rank
            item.save()

            # Backfill existing InventoryItem rows so players keep stats
            for inv in InventoryItem.objects.filter(item=item):
                if not inv.stat_bonuses:
                    rules = BOSS_RANK_STATS[rank]
                    chosen_stats = random.sample(POSSIBLE_STATS, rules["count"])
                    rolled_stats = {
                        s: random.randint(rules["min"], rules["max"])
                        for s in chosen_stats
                    }
                    inv.stat_bonuses = rolled_stats
                    inv.save(update_fields=["stat_bonuses"])
        except Item.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_inventoryitem_stat_bonuses_item_boss_rank_and_more"),
    ]

    operations = [
        migrations.RunPython(
            backfill_boss_drops, reverse_code=migrations.RunPython.noop
        ),
    ]
