# Generated by Django 5.1.4 on 2026-07-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_backfill_boss_drops"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="unique_subjects_today",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
