# Generated by Django 5.1.4 on 2026-07-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_userstats_unique_subjects_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='void_clarity_last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
