# Generated by Django 5.1.4 on 2026-07-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_add_void_clarity_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="humanities_xp",
            field=models.FloatField(default=0.0, verbose_name="Humanities XP"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_daily_cron_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Последний крон дейликов"
            ),
        ),
    ]
