# Generated by Django 5.1.4 on 2026-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_add_party_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="seen_guides",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Просмотренные гайды"
            ),
        ),
    ]
