# Generated by Django 5.1.4 on 2026-07-03 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_userprofile_analytics_enabled_featureevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="analytics_enabled",
        ),
        migrations.AddField(
            model_name="task",
            name="scheduled_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время (календарь)"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="show_in_calendar",
            field=models.BooleanField(
                default=False, verbose_name="Показывать в календаре"
            ),
        ),
        migrations.AlterField(
            model_name="featureevent",
            name="event_name",
            field=models.CharField(max_length=128, verbose_name="Имя события"),
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6", max_length=15, verbose_name="Цвет"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие календаря",
                "verbose_name_plural": "События календаря",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
