# Generated by Django 5.1.4 on 2026-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_remove_userprofile_analytics_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="analytics_enabled",
            field=models.BooleanField(default=True, verbose_name="Аналитика включена"),
        ),
    ]
