# Generated by Django 5.1.4 on 2026-07-04 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_userprofile_is_premium_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="last_streak_update_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="party",
            name="streak",
            field=models.PositiveIntegerField(default=0, verbose_name="Party Streak"),
        ),
        migrations.AddField(
            model_name="partymembership",
            name="last_buff_sent_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partymembership",
            name="last_daily_completed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partymembership",
            name="weekly_xp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partymembership",
            name="weekly_xp_reset_week",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.CreateModel(
            name="PartyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("task", "Task Completed"),
                            ("level_up", "Level Up"),
                            ("ally_unlock", "Ally Unlocked"),
                            ("milestone", "Milestone Reached"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_events",
                        to="api.partymembership",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Event",
                "verbose_name_plural": "Party Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartyEventReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=10)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="api.partyevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Event Reaction",
                "verbose_name_plural": "Party Event Reactions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"), name="unique_user_event_reaction"
                    )
                ],
            },
        ),
    ]
