# Generated by Django 6.0.6 on 2026-07-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_party_last_streak_update_date_party_streak_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_login_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Последний логин (Дата)"
            ),
        ),
    ]
