# Generated by Django 5.1.4 on 2026-07-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_userprofile_last_login_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                default="UTC", max_length=50, verbose_name="Timezone"
            ),
        ),
    ]
