# Generated by Django 5.1.4 on 2026-07-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_add_perf_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activeeffect",
            new_name="api_activee_user_id_7a1a09_idx",
            old_name="api_activeeffect_user_skill_idx",
        ),
        migrations.RenameIndex(
            model_name="bossencounter",
            new_name="api_bossenc_user_id_613232_idx",
            old_name="api_boss_user_defeated_idx",
        ),
        migrations.RenameIndex(
            model_name="inventoryitem",
            new_name="api_invento_user_pr_2571fb_idx",
            old_name="api_inventoryitem_profile_equipped_idx",
        ),
        migrations.RenameIndex(
            model_name="trainingsession",
            new_name="api_trainin_user_pr_8fd43c_idx",
            old_name="api_trainingsession_profile_date_idx",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="johan_recruited",
            field=models.BooleanField(default=False, verbose_name="Johan Recruited"),
        ),
    ]
