# Generated by Django 5.1.4 on 2026-07-06 09:49

from django.db import migrations


def delete_johan_recruited_allies(apps, schema_editor):
    RecruitedAlly = apps.get_model("api", "RecruitedAlly")
    RecruitedAlly.objects.filter(ally_code="johan").delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0049_rename_api_activeeffect_user_skill_idx_api_activee_user_id_7a1a09_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(delete_johan_recruited_allies),
        migrations.RemoveField(
            model_name="userprofile",
            name="johan_recruited",
        ),
    ]
