# Generated by Django 6.0.6 on 2026-07-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_remove_userprofile_johan_recruited"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="active_allies",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Активные союзники"
            ),
        ),
    ]
