# Generated by Django 5.1.4 on 2026-07-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_userprofile_active_allies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gc_ceiling",
            field=models.FloatField(default=105.0, verbose_name="Gc Ceiling"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gf_ceiling",
            field=models.FloatField(default=105.0, verbose_name="Gf Ceiling"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ps_ceiling",
            field=models.FloatField(default=105.0, verbose_name="Ps Ceiling"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="vm_ceiling",
            field=models.FloatField(default=105.0, verbose_name="Vm Ceiling"),
        ),
    ]
