# Generated by Django 5.1.4 on 2026-07-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_alter_userprofile_gc_ceiling_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partymembership",
            name="weekly_xp_reset_week",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
