# Generated by Django 5.1.4 on 2026-07-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_fix_weekly_xp_reset_week_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_weekly_reset",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Неделя последнего сброса",
            ),
        ),
    ]
