# Generated by Django 5.1.4 on 2026-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_userprofile_last_weekly_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_guest",
            field=models.BooleanField(default=False, verbose_name="Гость"),
        ),
    ]
