# Generated by Django 5.1.4 on 2026-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_userprofile_is_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_completed_category",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Категория последней задачи (tunnel_vision)",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_deja_vu_use",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее использование deja_vu"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="same_category_streak",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Стрик одной категории (tunnel_vision)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasks_completed_today",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Выполнено задач сегодня (momentum)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_overdue_tasks",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Всего просрочено/провалено (weight_of_history)"
            ),
        ),
    ]
