# Generated by Django 5.1.4 on 2026-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_userprofile_last_completed_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="icon",
            field=models.CharField(
                blank=True, default="", max_length=20, null=True, verbose_name="Иконка"
            ),
        ),
    ]
