# Generated by Django 5.1.4 on 2026-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки push-уведомлений'),
        ),
    ]
