# Generated by Django 5.1.4 on 2026-07-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_userprofile_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anonymous_mode',
            field=models.BooleanField(default=False, verbose_name='Анонимный режим'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='character_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Имя персонажа'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rival_visibility',
            field=models.BooleanField(default=True, verbose_name='Видимость для соперника'),
        ),
    ]
