# Generated by Django 5.1.4 on 2026-07-11 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_userprofile_anonymous_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bossencounter",
            name="last_idle_tick_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Последний тик урона",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_seen_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Был в сети"),
        ),
    ]
