# Generated by Django 5.1.4 on 2026-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_bossencounter_last_idle_tick_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_seen_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Был в сети"),
        ),
    ]
