# Generated by Django 5.1.4 on 2026-07-12 17:52

from django.db import migrations, models


def migrate_weekly_xp(apps, schema_editor):
    PartyMembership = apps.get_model("api", "PartyMembership")

    # Safely migrate existing weekly_xp to the UserProfile so users don't drop to 0
    memberships = PartyMembership.objects.select_related("user__profile").all()
    for membership in memberships:
        if hasattr(membership.user, "profile"):
            profile = membership.user.profile
            profile.weekly_xp = membership.weekly_xp
            profile.weekly_xp_reset_week = membership.weekly_xp_reset_week
            profile.save(update_fields=["weekly_xp", "weekly_xp_reset_week"])


def reverse_migrate_weekly_xp(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_alter_userprofile_last_seen_at"),
    ]

    operations = [
        # 1. Add new fields to UserProfile
        migrations.AddField(
            model_name="userprofile",
            name="weekly_xp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weekly_xp_reset_week",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        # 2. Run Data Migration (copying data)
        migrations.RunPython(migrate_weekly_xp, reverse_migrate_weekly_xp),
        # 3. Remove old fields from PartyMembership
        migrations.RemoveField(
            model_name="partymembership",
            name="weekly_xp",
        ),
        migrations.RemoveField(
            model_name="partymembership",
            name="weekly_xp_reset_week",
        ),
    ]
