# Generated by Django 5.1.4 on 2026-07-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_move_weekly_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dismissed_insights",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Скрытые инсайты"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_insight_dismissed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время последнего скрытия инсайта"
            ),
        ),
    ]
