# Generated by Django 5.1.4 on 2026-07-13 15:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_userprofile_dismissed_insights_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PomodoroSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Дата сессии"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время старта"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=25, verbose_name="Длительность (мин)"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        default="focus", max_length=20, verbose_name="Режим"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Лейбл фокуса"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=True, verbose_name="Завершена"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pomodoro_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия помодоро",
                "verbose_name_plural": "Сессии помодоро",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="api_pomodor_user_id_61f1ea_idx"
                    )
                ],
            },
        ),
    ]
