# Generated by Django 5.1.4 on 2026-07-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_pomodorosession"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pomodoro_settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Настройки помодоро"
            ),
        ),
    ]
