# Generated by Django 5.1.4 on 2026-07-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_userprofile_pomodoro_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_weekdays',
            field=models.PositiveSmallIntegerField(default=127, verbose_name='Дни повторения'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания (календарь)'),
        ),
    ]
