# Generated by Django 5.1.4 on 2026-07-15 10:51

from django.db import migrations, models


def backfill_mastery_category(apps, schema_editor):
    Task = apps.get_model('api', 'Task')
    KEYWORDS = {
        "sciences": ['math', 'physic', 'chemist', 'biolog', 'science', 'coding', 'coder', 'program', 'comput', 'chess', 'logic', 'stem'],
        "body": ['run', 'exercise', 'gym', 'sport', 'workout', 'fitness', 'sleep', 'shower', 'nutrit', 'diet', 'walk', 'cardio', 'stretch', 'train'],
        "languages": ['english', 'german', 'french', 'vocab', 'languag', 'spanish', 'chinese', 'russian', 'japanese', 'italian', 'swedish', 'korean'],
        "spirit": ['prayer', 'meditat', 'mindful', 'spirit', 'yoga', 'breath', 'zen', 'contemplat'],
        "humanities": ['histor', 'philosoph', 'read', 'writ', 'art', 'music', 'paint', 'draw', 'book', 'literat', 'humanit', 'cultur']
    }
    for task in Task.objects.filter(task_type='button'):
        title_lower = task.title.lower() if task.title else ""
        guessed = ""
        for cat, keywords in KEYWORDS.items():
            if any(kw in title_lower for kw in keywords):
                guessed = cat
                break
        task.mastery_category = guessed
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_task_repeat_weekdays_task_scheduled_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mastery_category',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Категория мастерства'),
        ),
        migrations.RunPython(backfill_mastery_category, reverse_code=migrations.RunPython.noop),
    ]
