# Generated by Django 5.1.4 on 2026-07-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_task_mastery_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="LootChest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chest_type",
                    models.CharField(
                        choices=[
                            ("standard_cache", "Standard Cache"),
                            ("quantum_safe", "Quantum Safe"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Тип сундука",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "cost_gold",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Стоимость (Gold)"
                    ),
                ),
                (
                    "drop_rates",
                    models.JSONField(
                        default=dict,
                        verbose_name="Шансы выпадения по gear_class (JSON)",
                    ),
                ),
                (
                    "icon_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="URL иконки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лут-сундук",
                "verbose_name_plural": "Лут-сундуки",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="gear_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "Scrap"),
                    ("D", "Integrated"),
                    ("C", "Enhanced"),
                    ("B", "Advanced"),
                    ("A", "Elite"),
                    ("S", "Anomaly"),
                ],
                default="E",
                max_length=1,
                null=True,
                verbose_name="Gear Class (E–S): Scrap/Integrated/Enhanced/Advanced/Elite/Anomaly",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("shop", "Shop"),
                    ("boss_drop", "Boss Drop"),
                    ("quest_reward", "Quest Reward"),
                    ("chest", "Chest Drop"),
                ],
                default="shop",
                max_length=20,
            ),
        ),
    ]
