# Generated by Django 5.1.4 on 2026-07-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_add_gear_class_and_loot_chest"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitedally",
            name="total_xp_received",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Получено опыта (Twin Souls)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="chronomancer_banked_days",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Запасные дни Chronomancer"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_chronomancer_used",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Последнее использование Chronomancer",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ledger_gold",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Золото в сейфе (Gambler's Ledger)"
            ),
        ),
    ]
