# Generated by Django 6.0.6 on 2026-07-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_recruitedally_total_xp_received_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="grier_revenge_charges",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Заряды возмездия Гриера"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_decoy_shadow_used",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Последнее использование Decoy Shadow",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_temporal_rewind_used",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Последнее использование Temporal Rewind",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_time_paradox_used",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Последнее использование Time Paradox",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="time_paradox_charges",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Заряды временного парадокса"
            ),
        ),
    ]
