# Generated by Django 6.0.6 on 2026-07-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_userprofile_grier_revenge_charges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_chaos_control_used",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Последнее использование Chaos Control",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_dark_sacrifice_used",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Последнее использование Dark Sacrifice",
            ),
        ),
    ]
