# Generated by Django 5.1.4 on 2026-07-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_userprofile_last_chaos_control_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="equipped_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Экипированный титул ID",
            ),
        ),
    ]
