# Generated by Django 6.0.6 on 2026-07-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_userprofile_equipped_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="partymembership",
            name="role",
            field=models.CharField(
                choices=[("OWNER", "Owner"), ("MEMBER", "Member")],
                default="MEMBER",
                max_length=10,
                verbose_name="Role",
            ),
        ),
    ]
