# Generated by Django 6.0.6 on 2026-07-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_partymembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="chests_opened",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userstats",
            name="items_crafted",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userstats",
            name="items_purchased",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userstats",
            name="potions_consumed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
