# Generated by Django 6.0.6 on 2026-07-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0076_rename_rank_f_to_e"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="unlocked_playstyle_titles",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Разблокированные титулы"
            ),
        ),
        migrations.AddField(
            model_name="userstats",
            name="boss_attacks_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество атак на боссов"
            ),
        ),
    ]
