# Generated by Django 6.0.6 on 2026-07-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0077_userprofile_unlocked_playstyle_titles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="category_streaks",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Стрики по категориям"
            ),
        ),
    ]
