# Generated by Django 6.0.6 on 2026-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_userprofile_category_streaks"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dailies_completed_today",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Выполнено дейликов сегодня"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="habits_completed_today",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Выполнено привычек сегодня"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="todos_completed_today",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Выполнено тудушек сегодня"
            ),
        ),
    ]
