# Generated by Django 6.0.6 on 2026-07-20 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0079_userprofile_dailies_completed_today_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activeeffect",
            name="effect_id",
            field=models.CharField(
                help_text="Уникальный идентификатор: blueprint_effect, iron_fast_effect...",
                max_length=80,
                verbose_name="ID эффекта",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activeeffect",
            unique_together={("user", "effect_id")},
        ),
    ]
