# Generated by Django 5.1.4 on 2026-07-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0080_alter_activeeffect_effect_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gear_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "Scrap"),
                    ("D", "Integrated"),
                    ("C", "Enhanced"),
                    ("B", "Advanced"),
                    ("A", "Elite"),
                    ("S", "Anomaly"),
                    ("SS", "Transcendent"),
                    ("SSS", "Singularity"),
                ],
                default="E",
                max_length=3,
                null=True,
                verbose_name="Gear Class (E–SSS): Scrap/Integrated/Enhanced/Advanced/Elite/Anomaly/Transcendent/Singularity",
            ),
        ),
    ]
