# Generated by Django 6.0.6 on 2026-07-23 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_gear_class_ss_sss'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_activity_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключ активности')),
                ('duration_minutes', models.PositiveIntegerField(default=25, verbose_name='Длительность (мин)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время старта')),
                ('is_paused', models.BooleanField(default=False, verbose_name='Пауза')),
                ('paused_remaining_seconds', models.PositiveIntegerField(default=0, verbose_name='Остаток секунд на паузе')),
                ('mode', models.CharField(default='work', max_length=20, verbose_name='Режим')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_pomodoro', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активная сессия помодоро',
                'verbose_name_plural': 'Активные сессии помодоро',
            },
        ),
    ]
