# Generated by Django 6.0.6 on 2026-07-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0082_activepomodorosession"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=140, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="member_cap",
            field=models.PositiveSmallIntegerField(
                default=8,
                help_text="Max members allowed (2–8).",
                verbose_name="Member cap",
            ),
        ),
        migrations.CreateModel(
            name="PartyAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("streak_7", "7-Day Streak"),
                            ("streak_30", "30-Day Streak"),
                            ("streak_100", "100-Day Streak"),
                            ("full_house", "Full House (max members)"),
                            ("first_quest", "First Weekly Quest Completed"),
                            ("quest_master", "5 Weekly Quests Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="api.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Achievement",
                "verbose_name_plural": "Party Achievements",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("party", "code"), name="unique_party_achievement"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PartyWeeklyQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quest_type",
                    models.CharField(
                        choices=[
                            ("tasks_completed", "Tasks Completed"),
                            ("habits_completed", "Habits Completed"),
                        ],
                        default="tasks_completed",
                        max_length=30,
                    ),
                ),
                ("target_value", models.PositiveIntegerField(default=50)),
                ("current_value", models.PositiveIntegerField(default=0)),
                (
                    "week_key",
                    models.CharField(
                        help_text="ISO week key, e.g. '25W30'", max_length=10
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_quests",
                        to="api.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Weekly Quest",
                "verbose_name_plural": "Party Weekly Quests",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("party", "week_key"), name="unique_party_week_quest"
                    )
                ],
            },
        ),
    ]
