# Generated by Django 5.1.4 on 2026-08-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_seed_all_consumables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='party',
            name='quest_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Consecutive Quests Completed'),
        ),
        migrations.AlterField(
            model_name='partyevent',
            name='event_type',
            field=models.CharField(choices=[('task', 'Task Completed'), ('level_up', 'Level Up'), ('buff_sent', 'Buff Sent'), ('rank_up', 'Rank Up'), ('ally_unlock', 'Ally Unlocked'), ('milestone', 'Milestone Reached'), ('chat', 'Chat Message')], max_length=20),
        ),
    ]
