# Generated by Django 6.0.6 on 2026-08-23 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0089_party_quest_streak_chat_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "calories_per_100",
                    models.FloatField(verbose_name="Калории на 100г/мл"),
                ),
                (
                    "protein_per_100",
                    models.FloatField(default=0.0, verbose_name="Белки на 100г/мл"),
                ),
                (
                    "fat_per_100",
                    models.FloatField(default=0.0, verbose_name="Жиры на 100г/мл"),
                ),
                (
                    "carbs_per_100",
                    models.FloatField(default=0.0, verbose_name="Углеводы на 100г/мл"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Граммы"),
                            ("ml", "Миллилитры"),
                            ("pcs", "Штуки"),
                        ],
                        default="g",
                        max_length=5,
                        verbose_name="Единица",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="Избранное"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["-is_favorite", "name"],
            },
        ),
        migrations.CreateModel(
            name="MealEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Завтрак"),
                            ("lunch", "Обед"),
                            ("dinner", "Ужин"),
                            ("snack", "Снэк"),
                        ],
                        default="snack",
                        max_length=20,
                        verbose_name="Приём пищи",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="Количество (г/мл/шт)")),
                ("calories", models.FloatField(verbose_name="Калории")),
                ("protein", models.FloatField(default=0.0, verbose_name="Белки")),
                ("fat", models.FloatField(default=0.0, verbose_name="Жиры")),
                ("carbs", models.FloatField(default=0.0, verbose_name="Углеводы")),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="Заметка"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_entries",
                        to="api.fooditem",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись питания",
                "verbose_name_plural": "Записи питания",
                "ordering": ["date", "meal_type", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="NutriGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calories",
                    models.FloatField(default=2000.0, verbose_name="Цель ккал/день"),
                ),
                (
                    "protein",
                    models.FloatField(default=150.0, verbose_name="Цель белки г/день"),
                ),
                (
                    "fat",
                    models.FloatField(default=65.0, verbose_name="Цель жиры г/день"),
                ),
                (
                    "carbs",
                    models.FloatField(
                        default=250.0, verbose_name="Цель углеводы г/день"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutri_goal",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель питания",
                "verbose_name_plural": "Цели питания",
            },
        ),
        migrations.AddIndex(
            model_name="fooditem",
            index=models.Index(
                fields=["user", "is_favorite"], name="api_foodite_user_id_018ab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fooditem",
            index=models.Index(
                fields=["user", "name"], name="api_foodite_user_id_c7d012_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealentry",
            index=models.Index(
                fields=["user", "date"], name="api_mealent_user_id_37b1c4_idx"
            ),
        ),
    ]
