# Generated by Django 6.0.6 on 2026-08-23 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0090_nutrition_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mealentry",
            name="photo_url",
            field=models.TextField(blank=True, default="", verbose_name="Фото блюда"),
        ),
        migrations.AddField(
            model_name="nutrigoal",
            name="water_ml",
            field=models.PositiveIntegerField(
                default=2000, verbose_name="Цель вода мл/день"
            ),
        ),
        migrations.CreateModel(
            name="GlobalFoodCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Бренд"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="Штрихкод",
                    ),
                ),
                (
                    "calories_per_100",
                    models.FloatField(default=0.0, verbose_name="Ккал на 100г"),
                ),
                (
                    "protein_per_100",
                    models.FloatField(default=0.0, verbose_name="Белки на 100г"),
                ),
                (
                    "fat_per_100",
                    models.FloatField(default=0.0, verbose_name="Жиры на 100г"),
                ),
                (
                    "carbs_per_100",
                    models.FloatField(default=0.0, verbose_name="Углеводы на 100г"),
                ),
                (
                    "unit",
                    models.CharField(default="g", max_length=5, verbose_name="Единица"),
                ),
                (
                    "image_url",
                    models.TextField(
                        blank=True, default="", verbose_name="Ссылка на фото"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="openfoodfacts", max_length=32, verbose_name="Источник"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Глобальный продукт (кеш)",
                "verbose_name_plural": "Глобальные продукты (кеш)",
                "indexes": [
                    models.Index(fields=["name"], name="api_globalf_name_f6c152_idx"),
                    models.Index(
                        fields=["barcode"], name="api_globalf_barcode_9ef00a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedMealCombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название комбо"),
                ),
                (
                    "default_meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Завтрак"),
                            ("lunch", "Обед"),
                            ("dinner", "Ужин"),
                            ("snack", "Снэк"),
                        ],
                        default="breakfast",
                        max_length=20,
                        verbose_name="Приём по умолчанию",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_meal_combos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сохранённое комбо блюд",
                "verbose_name_plural": "Сохранённые комбо блюд",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MealComboItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        default=100.0, verbose_name="Количество (г/мл/шт)"
                    ),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combo_items",
                        to="api.fooditem",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.savedmealcombo",
                        verbose_name="Комбо",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент комбо",
                "verbose_name_plural": "Элементы комбо",
            },
        ),
        migrations.CreateModel(
            name="WaterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                (
                    "amount_ml",
                    models.PositiveIntegerField(default=0, verbose_name="Выпито мл"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог воды",
                "verbose_name_plural": "Логи воды",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="unique_user_daily_water"
                    )
                ],
            },
        ),
    ]
