# Generated by Django 5.1.4 on 2026-08-27 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_add_apex_sovereign_loot_chests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('study', 'Предмет / Учёба'), ('habit_pos', 'Привычка (+)'), ('habit_neg', 'Привычка (-)'), ('daily', 'Дейлик'), ('daily_uncomplete', 'Отмена дейлика'), ('todo', 'To-Do'), ('todo_uncomplete', 'Отмена To-Do'), ('pomodoro', 'Помодоро')], default='study', max_length=20, verbose_name='Тип активности')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(blank=True, default='Other', max_length=50, verbose_name='Категория')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Иконка')),
                ('hours', models.FloatField(default=0.0, verbose_name='Часы')),
                ('focus_rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг фокуса')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='Полученный опыт')),
                ('gold_earned', models.IntegerField(default=0, verbose_name='Полученное золото')),
                ('hp_lost', models.IntegerField(default=0, verbose_name='Потерянное HP')),
                ('mana_gained', models.IntegerField(default=0, verbose_name='Полученная мана')),
                ('boss_damage', models.IntegerField(default=0, verbose_name='Урон боссу')),
                ('streak_value', models.IntegerField(default=0, verbose_name='Значение стрика')),
                ('difficulty', models.CharField(blank=True, default='medium', max_length=20, verbose_name='Сложность')),
                ('cognitive_gains', models.JSONField(blank=True, default=dict, verbose_name='Когнитивные приросты')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='api.task', verbose_name='Связанная задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог активности',
                'verbose_name_plural': 'Логи активности',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_useract_user_id_18a164_idx'), models.Index(fields=['user', 'activity_type', 'created_at'], name='api_useract_user_id_a9c349_idx')],
            },
        ),
    ]
