# Generated by Django 5.1.4 on 2026-08-27 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_useractivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='fiber_per_100',
            field=models.FloatField(blank=True, null=True, verbose_name='Клетчатка на 100г'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='last_used_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последнее использование'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='saturated_fat_per_100',
            field=models.FloatField(blank=True, null=True, verbose_name='Нас. жиры на 100г'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sodium_per_100',
            field=models.FloatField(blank=True, null=True, verbose_name='Натрий на 100г (мг)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sugar_per_100',
            field=models.FloatField(blank=True, null=True, verbose_name='Сахар на 100г'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='use_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество использований'),
        ),
        migrations.AddField(
            model_name='globalfoodcache',
            name='fiber_per_100',
            field=models.FloatField(blank=True, null=True, verbose_name='Клетчатка на 100г'),
        ),
        migrations.AddField(
            model_name='globalfoodcache',
            name='saturated_fat_per_100',
            field=models.FloatField(blank=True, null=True, verbose_name='Нас. жиры на 100г'),
        ),
        migrations.AddField(
            model_name='globalfoodcache',
            name='sodium_per_100',
            field=models.FloatField(blank=True, null=True, verbose_name='Натрий на 100г (мг)'),
        ),
        migrations.AddField(
            model_name='globalfoodcache',
            name='sugar_per_100',
            field=models.FloatField(blank=True, null=True, verbose_name='Сахар на 100г'),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='fiber',
            field=models.FloatField(blank=True, null=True, verbose_name='Клетчатка'),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='saturated_fat',
            field=models.FloatField(blank=True, null=True, verbose_name='Нас. жиры'),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='sodium',
            field=models.FloatField(blank=True, null=True, verbose_name='Натрий (мг)'),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='sugar',
            field=models.FloatField(blank=True, null=True, verbose_name='Сахар'),
        ),
        migrations.AddField(
            model_name='nutrigoal',
            name='reminder_breakfast',
            field=models.TimeField(blank=True, null=True, verbose_name='Напоминание завтрак'),
        ),
        migrations.AddField(
            model_name='nutrigoal',
            name='reminder_dinner',
            field=models.TimeField(blank=True, null=True, verbose_name='Напоминание ужин'),
        ),
        migrations.AddField(
            model_name='nutrigoal',
            name='reminder_lunch',
            field=models.TimeField(blank=True, null=True, verbose_name='Напоминание обед'),
        ),
        migrations.AddField(
            model_name='nutrigoal',
            name='target_weight_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Целевой вес (кг)'),
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('weight_kg', models.FloatField(verbose_name='Вес (кг)')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись веса',
                'verbose_name_plural': 'Записи веса',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_weight')],
            },
        ),
    ]
