# Generated by Django 5.1.4 on 2026-08-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0095_nutrition_v2_micronutrients_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("study", "Предмет / Учёба"),
                    ("habit_pos", "Привычка (+)"),
                    ("habit_neg", "Привычка (-)"),
                    ("daily", "Дейлик"),
                    ("daily_uncomplete", "Отмена дейлика"),
                    ("todo", "To-Do"),
                    ("todo_uncomplete", "Отмена To-Do"),
                    ("pomodoro", "Помодоро"),
                    ("achievement", "Достижение"),
                    ("boss_defeat", "Победа над боссом"),
                ],
                default="study",
                max_length=20,
                verbose_name="Тип активности",
            ),
        ),
    ]
