# Generated by Django 5.1.4 on 2026-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_userprofile_history_backfilled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_mutator_tick_at',
            field=models.DateField(blank=True, null=True, verbose_name='Последний тик мутаторов'),
        ),
    ]
