# Generated by Django 5.1.4 on 2026-09-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_boss_reward_sp_and_rebalance_drops'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_party_task_names',
            field=models.BooleanField(default=False, verbose_name='Скрывать названия задач в группе'),
        ),
    ]
