# Generated by Django 5.1.4 on 2026-09-13 21:41

import time
from django.db import migrations, models
from django.db.models import Q


def restore_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("api", "UserProfile")
    UserStats = apps.get_model("api", "UserStats")
    UserActivityLog = apps.get_model("api", "UserActivityLog")
    Boss = apps.get_model("api", "Boss")
    BossEncounter = apps.get_model("api", "BossEncounter")
    Item = apps.get_model("api", "Item")
    InventoryItem = apps.get_model("api", "InventoryItem")

    # 1. Normalize active_mutators for all profiles from list to dict if needed
    for p in UserProfile.objects.all():
        raw = p.active_mutators
        if isinstance(raw, list):
            active = [m for m in raw if isinstance(m, dict)]
            purchased = [
                m if isinstance(m, str) else m.get("id")
                for m in raw
                if m
            ]
            p.active_mutators = {"active": active, "purchased": purchased}
            p.save(update_fields=["active_mutators"])
        elif not isinstance(raw, dict):
            p.active_mutators = {"active": [], "purchased": []}
            p.save(update_fields=["active_mutators"])

    # 2. Specifically credit KubsonMercer & kubsonpage3
    users = User.objects.filter(
        Q(username__iexact="KubsonMercer")
        | Q(username__iexact="kubsonmercer")
        | Q(username__icontains="kubson")
        | Q(email__icontains="kubson")
    )

    jackal_boss = Boss.objects.filter(id_name="herald_jackal").first()
    fang_item = Item.objects.filter(code="heralds_fang").first()
    now_ms = int(time.time() * 1000)

    for u in users:
        profile = UserProfile.objects.filter(user=u).first()
        stats, _ = UserStats.objects.get_or_create(user=u)

        if profile:
            # 2a. Credit bloodwork and chronomancer mutators
            current_mut = profile.active_mutators
            if not isinstance(current_mut, dict):
                current_mut = {"active": [], "purchased": []}

            purchased = list(current_mut.get("purchased", []))
            for mid in ["bloodwork", "chronomancer"]:
                if mid not in purchased:
                    purchased.append(mid)

            active = list(current_mut.get("active", []))
            active_ids = [m.get("id") if isinstance(m, dict) else m for m in active]
            if "chronomancer" not in active_ids and len(active) < 3:
                active.append(
                    {
                        "id": "chronomancer",
                        "activatedAt": now_ms,
                        "duration": None,
                    }
                )

            profile.active_mutators = {"active": active, "purchased": purchased}
            profile.save(update_fields=["active_mutators"])

            # 2b. Grant Herald's Fang item
            if fang_item:
                inv_item, created = InventoryItem.objects.get_or_create(
                    user_profile=profile,
                    item=fang_item,
                    defaults={"stat_bonuses": {"pwr": 2, "spd": 1}},
                )
                if not created and not inv_item.stat_bonuses:
                    inv_item.stat_bonuses = {"pwr": 2, "spd": 1}
                    inv_item.save(update_fields=["stat_bonuses"])

        # 2c. Ensure Herald Jackal encounter is marked as defeated
        if jackal_boss:
            enc = BossEncounter.objects.filter(user=u, boss=jackal_boss).first()
            if not enc:
                BossEncounter.objects.create(
                    user=u,
                    boss=jackal_boss,
                    hp_current=0,
                    is_defeated=True,
                    reward_multiplier=1.0,
                )
            elif not enc.is_defeated:
                enc.is_defeated = True
                enc.hp_current = 0
                enc.save(update_fields=["is_defeated", "hp_current"])

        # 2d. Record Herald Jackal defeat activity log if missing
        if not UserActivityLog.objects.filter(
            user=u,
            activity_type="boss_defeat",
            title__in=["Jackal's Howl", "Herald Jackal"],
        ).exists():
            UserActivityLog.objects.create(
                user=u,
                activity_type="boss_defeat",
                title="Jackal's Howl",
                xp_earned=35,
                gold_earned=250,
                metadata={
                    "boss_level": 2,
                    "sp_reward": 5,
                    "item_dropped": "heralds_fang",
                    "item_name": "Herald's Fang",
                },
            )

        # 2e. Sync bosses_defeated count
        defeated_count = BossEncounter.objects.filter(user=u, is_defeated=True).count()
        if stats.bosses_defeated < defeated_count:
            stats.bosses_defeated = defeated_count
            stats.save(update_fields=["bosses_defeated"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0117_correct_ink_warden_rewards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="active_mutators",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Активные мутаторы"
            ),
        ),
        migrations.RunPython(restore_data, migrations.RunPython.noop),
    ]
