# Generated by Django 5.1.4 on 2026-09-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0119_regrant_kubsonmercer_mutators"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hidden_activities",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Скрытые активности"
            ),
        ),
    ]
