# Generated by Django 5.1.4 on 2026-09-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0120_add_hidden_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_habit_fail_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_sanctuary_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
