# Generated by Django 5.1.4 on 2026-09-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0121_userprofile_last_habit_fail_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activities_completed_today",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Выполнено активностей сегодня (volatile)"
            ),
        ),
    ]
