# Generated by Django 5.1.4 on 2026-09-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0122_userprofile_activities_completed_today"),
    ]

    operations = [
        migrations.AddField(
            model_name="activepomodorosession",
            name="paused_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Поставлена на паузу"
            ),
        ),
    ]
