# Generated by Django 5.1.4 on 2026-09-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0123_activepomodorosession_paused_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="all_day",
            field=models.BooleanField(default=False, verbose_name="Весь день"),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_interval_weeks",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Повтор каждые N недель"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Начало повтора (якорь интервала)"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_until",
            field=models.DateField(blank=True, null=True, verbose_name="Повторять до"),
        ),
    ]
