# Generated by Django 5.1.4 on 2026-09-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0124_calendarevent_all_day_task_repeat_interval_weeks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_deadline_push_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
