# Generated by Django 5.1.4 on 2026-09-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0125_userprofile_last_deadline_push_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="calendar_feed_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
