# Generated by Django 5.1.4 on 2026-09-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_userprofile_calendar_feed_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='widget_sync_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
