# Generated by Django 5.1.4 on 2026-09-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_userprofile_widget_sync_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_rival_overtook_push_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
