# Constants for static data (like bosses)

SCROLL_BOSSES = [
    {
        "id": "misted_wanderer",
        "rank": "E",
        "name": "Misted Wanderer",
        "price": 50,
        "bossHP": 500,
        "reward": {"gold": 100, "xp": 50, "mp": 10, "sp": 1},
        "uniqueItem": "wanderers_hood",
    },
    {
        "id": "nameless_bones",
        "rank": "E",
        "name": "Nameless Bones",
        "price": 60,
        "bossHP": 600,
        "reward": {"gold": 120, "xp": 60, "mp": 10, "sp": 1},
        "uniqueItem": "bone_bracelet",
    },
    {
        "id": "herald_jackal",
        "rank": "D",
        "name": "Jackal's Howl",
        "price": 120,
        "bossHP": 1500,
        "reward": {"gold": 250, "xp": 150, "mp": 15, "sp": 2},
        "uniqueItem": "heralds_fang",
    },
    {
        "id": "ink_warden",
        "rank": "D",
        "name": "Ink Mark",
        "price": 130,
        "bossHP": 1800,
        "reward": {"gold": 280, "xp": 180, "mp": 15, "sp": 2},
        "uniqueItem": "wardens_quill",
    },
    {
        "id": "abyssal_bellringer",
        "rank": "C",
        "name": "Echoing Bell",
        "price": 220,
        "bossHP": 3500,
        "reward": {"gold": 500, "xp": 300, "mp": 20, "sp": 3},
        "uniqueItem": "echo_bell",
    },
    {
        "id": "frost_executioner",
        "rank": "C",
        "name": "Bloodfrost",
        "price": 230,
        "bossHP": 4000,
        "reward": {"gold": 550, "xp": 350, "mp": 20, "sp": 3},
        "uniqueItem": "frostbite_blade",
    },
    {
        "id": "weaving_shade",
        "rank": "C",
        "name": "Spinning Silk",
        "price": 210,
        "bossHP": 3200,
        "reward": {"gold": 480, "xp": 280, "mp": 20, "sp": 3},
        "uniqueItem": "silk_mantle",
    },
    {
        "id": "ember_smith",
        "rank": "B",
        "name": "Forge Wrath",
        "price": 380,
        "bossHP": 8000,
        "reward": {"gold": 900, "xp": 600, "mp": 30, "sp": 5},
        "uniqueItem": "ember_gauntlet",
    },
    {
        "id": "sanctuary_weeper",
        "rank": "B",
        "name": "Sanctuary's Tear",
        "price": 390,
        "bossHP": 9000,
        "reward": {"gold": 950, "xp": 650, "mp": 30, "sp": 5},
        "uniqueItem": "glass_tear",
    },
    {
        "id": "shallow_leviathan",
        "rank": "B",
        "name": "Black Tide",
        "price": 400,
        "bossHP": 10000,
        "reward": {"gold": 1000, "xp": 700, "mp": 30, "sp": 5},
        "uniqueItem": "leviathan_scale",
    },
    {
        "id": "faceless_king",
        "rank": "A",
        "name": "Ashen Name",
        "price": 650,
        "bossHP": 20000,
        "reward": {"gold": 2000, "xp": 1500, "mp": 50, "sp": 8},
        "uniqueItem": "crown_of_ash",
    },
    {
        "id": "ore_golem",
        "rank": "A",
        "name": "Mine's Groan",
        "price": 660,
        "bossHP": 22000,
        "reward": {"gold": 2200, "xp": 1600, "mp": 50, "sp": 8},
        "uniqueItem": "golems_grip",
    },
    {
        "id": "wounded_moon",
        "rank": "A",
        "name": "Lunar Scar",
        "price": 680,
        "bossHP": 25000,
        "reward": {"gold": 2500, "xp": 1800, "mp": 50, "sp": 8},
        "uniqueItem": "scar_shard",
    },
    {
        "id": "choir_forgotten",
        "rank": "S",
        "name": "Forgotten Choir",
        "price": 1100,
        "bossHP": 60000,
        "reward": {"gold": 5000, "xp": 4000, "mp": 80, "sp": 15},
        "uniqueItem": "forgotten_score",
    },
    {
        "id": "bottomless_miser",
        "rank": "S",
        "name": "Abyssal Greed",
        "price": 1150,
        "bossHP": 70000,
        "reward": {"gold": 6000, "xp": 4500, "mp": 80, "sp": 15},
        "uniqueItem": "abyssal_purse",
    },
    {
        "id": "winter_thorn",
        "rank": "S",
        "name": "Winter's Thorn",
        "price": 1200,
        "bossHP": 80000,
        "reward": {"gold": 7000, "xp": 5000, "mp": 80, "sp": 15},
        "uniqueItem": "winter_plate",
    },
    {
        "id": "king_ashen_throne",
        "rank": "SS",
        "name": "Ashen Throne",
        "price": 2000,
        "bossHP": 180000,
        "reward": {"gold": 15000, "xp": 12000, "mp": 120, "sp": 25},
        "uniqueItem": "throne_seal",
    },
    {
        "id": "eclipse_warden",
        "rank": "SS",
        "name": "Eclipse Eye",
        "price": 2100,
        "bossHP": 200000,
        "reward": {"gold": 18000, "xp": 14000, "mp": 120, "sp": 25},
        "uniqueItem": "eclipse_eye",
    },
    {
        "id": "nameless_god",
        "rank": "SSS",
        "name": "Nameless God",
        "price": 4000,
        "bossHP": 600000,
        "reward": {"gold": 50000, "xp": 40000, "mp": 200, "sp": 60},
        "uniqueItem": "mask_nameless",
    },
    {
        "id": "final_dusk",
        "rank": "SSS",
        "name": "Final Dusk",
        "price": 4200,
        "bossHP": 700000,
        "reward": {"gold": 60000, "xp": 50000, "mp": 200, "sp": 60},
        "uniqueItem": "blade_final_dusk",
    },
]

SCROLL_BOSSES_DICT = {b["id"]: b for b in SCROLL_BOSSES}


RANK_THRESHOLDS = [
    {"id": "F", "min": 0},
    {"id": "D", "min": 50},
    {"id": "C", "min": 150},
    {"id": "B", "min": 400},
    {"id": "A", "min": 800},
    {"id": "S", "min": 1500},
    {"id": "SS", "min": 2500},
    {"id": "SSS", "min": 4000},
]

TASK_REWARD_TABLE = {
    "trivial": {"xp": 1, "gold": 1},
    "easy": {"xp": 5, "gold": 3},
    "medium": {"xp": 15, "gold": 7},
    "hard": {"xp": 40, "gold": 15},
}

BOSS_DIFFICULTY_MULTIPLIERS = {
    "EASY": {"hp": 0.5, "reward": 0.8},
    "NORMAL": {"hp": 1.0, "reward": 1.0},
    "HARD": {"hp": 2.0, "reward": 1.5},
    "EXTREME": {"hp": 5.0, "reward": 2.5},
}
