import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mindos.settings")
django.setup()

from api.models import Item, ItemEffect, LootChest  # noqa: E402

items_data = [
    {
        "id": "neural_cap",
        "slot": "headware",
        "name": "Neural Cap",
        "gear_class": "E",
        "cost": 80,
        "stats": {"foc": 2},
    },
    {
        "id": "sync_visor",
        "slot": "headware",
        "name": "Sync Visor",
        "gear_class": "D",
        "cost": 200,
        "stats": {"foc": 2, "mem": 1},
    },
    {
        "id": "cognitive_crown",
        "slot": "headware",
        "name": "Cognitive Crown",
        "gear_class": "C",
        "cost": 500,
        "stats": {"foc": 2, "pwr": 2},
    },
    {
        "id": "transcendence_helm",
        "slot": "headware",
        "name": "Transcendence Helm",
        "gear_class": "B",
        "cost": 1500,
        "stats": {"foc": 5, "mem": 2},
    },
    {
        "id": "basic_cortex",
        "slot": "neural_link",
        "name": "Basic Cortex Link",
        "gear_class": "E",
        "cost": 60,
        "stats": {"mem": 2},
    },
    {
        "id": "dual_channel",
        "slot": "neural_link",
        "name": "Dual-Channel Adapter",
        "gear_class": "D",
        "cost": 180,
        "stats": {"mem": 2, "lck": 1},
    },
    {
        "id": "quantum_sync",
        "slot": "neural_link",
        "name": "Quantum Sync",
        "gear_class": "C",
        "cost": 450,
        "stats": {"mem": 4},
    },
    {
        "id": "void_bridge",
        "slot": "neural_link",
        "name": "Void Bridge",
        "gear_class": "B",
        "cost": 2000,
        "stats": {"mem": 5, "foc": 2},
    },
    {
        "id": "carbon_vest",
        "slot": "core",
        "name": "Carbon Vest",
        "gear_class": "E",
        "cost": 90,
        "stats": {"def": 2},
    },
    {
        "id": "reactive_shell",
        "slot": "core",
        "name": "Reactive Shell",
        "gear_class": "D",
        "cost": 220,
        "stats": {"def": 2, "pwr": 1},
    },
    {
        "id": "resonance_core",
        "slot": "core",
        "name": "Resonance Core",
        "gear_class": "C",
        "cost": 480,
        "stats": {"def": 4},
    },
    {
        "id": "singularity_engine",
        "slot": "core",
        "name": "Singularity Engine",
        "gear_class": "B",
        "cost": 2200,
        "stats": {"def": 5, "pwr": 2},
    },
    {
        "id": "training_implants",
        "slot": "arms",
        "name": "Training Implants",
        "gear_class": "E",
        "cost": 70,
        "stats": {"pwr": 2},
    },
    {
        "id": "force_amplifiers",
        "slot": "arms",
        "name": "Force Amplifiers",
        "gear_class": "D",
        "cost": 190,
        "stats": {"pwr": 2, "def": 1},
    },
    {
        "id": "synaptic_boosters",
        "slot": "arms",
        "name": "Synaptic Boosters",
        "gear_class": "C",
        "cost": 420,
        "stats": {"pwr": 2, "spd": 2},
    },
    {
        "id": "mobility_frame",
        "slot": "legs",
        "name": "Mobility Frame",
        "gear_class": "E",
        "cost": 75,
        "stats": {"spd": 2},
    },
    {
        "id": "overdrive_chassis",
        "slot": "legs",
        "name": "Overdrive Chassis",
        "gear_class": "D",
        "cost": 210,
        "stats": {"spd": 2, "lck": 1},
    },
    {
        "id": "phase_legs",
        "slot": "legs",
        "name": "Phase Legs",
        "gear_class": "C",
        "cost": 460,
        "stats": {"spd": 4},
    },
    {
        "id": "data_ring",
        "slot": "ring1",
        "name": "Data Ring",
        "gear_class": "E",
        "cost": 50,
        "stats": {"lck": 2},
    },
    {
        "id": "echo_ring",
        "slot": "ring1",
        "name": "Echo Ring",
        "gear_class": "D",
        "cost": 140,
        "stats": {"lck": 2, "mem": 1},
    },
    {
        "id": "null_ring",
        "slot": "ring2",
        "name": "Null Ring",
        "gear_class": "C",
        "cost": 380,
        "stats": {"lck": 2, "foc": 2},
    },
    {
        "id": "ashen_cap",
        "slot": "headware",
        "name": "Ashen Cap",
        "gear_class": "E",
        "cost": 60,
        "source": "chest",
        "description": "A helmet covered in the ash of a long-extinguished city.",
        "stats": {"foc": 1, "mem": 1},
    },
    {
        "id": "hollow_vest",
        "slot": "core",
        "name": "Hollow Vest",
        "gear_class": "E",
        "cost": 70,
        "source": "chest",
        "description": "Armour fashioned from the hull of a disassembled drone.",
        "stats": {"def": 2},
    },
    {
        "id": "frayed_link",
        "slot": "neural_link",
        "name": "Frayed Link",
        "gear_class": "E",
        "cost": 50,
        "source": "chest",
        "description": "A chip with cracked memory. Most of it is still there.",
        "stats": {"mem": 2},
    },
    {
        "id": "rootbound_legs",
        "slot": "legs",
        "name": "Rootbound Legs",
        "gear_class": "E",
        "cost": 65,
        "source": "chest",
        "description": "An exoskeleton that fused with its previous wearer.",
        "stats": {"spd": 2},
    },
    {
        "id": "shard_of_nothing",
        "slot": "ring1",
        "name": "Shard of Nothing",
        "gear_class": "E",
        "cost": 40,
        "source": "chest",
        "description": "A fragment of a ring. The other half does not exist.",
        "stats": {"lck": 1, "foc": 1},
    },
    {
        "id": "warden_brace",
        "slot": "arms",
        "name": "Warden's Brace",
        "gear_class": "E",
        "cost": 55,
        "source": "chest",
        "description": "The first tool of a lower-tier overseer. Still functional.",
        "stats": {"pwr": 2},
    },
    {
        "id": "pale_visor",
        "slot": "headware",
        "name": "Pale Visor",
        "gear_class": "D",
        "cost": 160,
        "source": "chest",
        "description": "Sees too much. Most prefer not to look.",
        "stats": {"foc": 3, "mem": 1},
    },
    {
        "id": "kindled_shell",
        "slot": "core",
        "name": "Kindled Shell",
        "gear_class": "D",
        "cost": 180,
        "source": "chest",
        "description": "Armour that survived three wars and two owners.",
        "stats": {"def": 3, "pwr": 1},
    },
    {
        "id": "whisper_node",
        "slot": "neural_link",
        "name": "Whisper Node",
        "gear_class": "D",
        "cost": 150,
        "source": "chest",
        "description": "Transmits messages that no one sent.",
        "stats": {"mem": 3, "lck": 1},
    },
    {
        "id": "pilgrim_legs",
        "slot": "legs",
        "name": "Pilgrim's Legs",
        "gear_class": "D",
        "cost": 170,
        "source": "chest",
        "description": "Worn by those who walked far and did not return.",
        "stats": {"spd": 3, "lck": 1},
    },
    {
        "id": "still_water_ring",
        "slot": "ring1",
        "name": "Ring of Still Water",
        "gear_class": "D",
        "cost": 130,
        "source": "chest",
        "description": "The surface is always calm. What lies beneath is unknown.",
        "stats": {"lck": 2, "foc": 2},
    },
    {
        "id": "chain_of_the_deep",
        "slot": "offhand",
        "name": "Chain of the Deep",
        "gear_class": "D",
        "cost": 145,
        "source": "chest",
        "description": "A chain from the bottom. No one knows what it once held.",
        "stats": {"mem": 2, "def": 2},
    },
    {
        "id": "echo_sigil",
        "slot": "ring2",
        "name": "Echo Sigil",
        "gear_class": "D",
        "cost": 140,
        "source": "chest",
        "description": "The symbol repeats in every mirror in this world.",
        "stats": {"mem": 2, "spd": 2},
    },
    {
        "id": "veil_of_dusk",
        "slot": "headware",
        "name": "Veil of Dusk",
        "gear_class": "C",
        "cost": 400,
        "source": "chest",
        "description": "Worn at sunset. Removed at dawn - if there is time.",
        "stats": {"foc": 4, "mem": 2, "lck": 1},
    },
    {
        "id": "ironbloom_plate",
        "slot": "core",
        "name": "Ironbloom Plate",
        "gear_class": "C",
        "cost": 450,
        "source": "chest",
        "description": "Armour etched with flowers that do not exist.",
        "stats": {"def": 5, "pwr": 2},
    },
    {
        "id": "laced_cortex",
        "slot": "neural_link",
        "name": "Laced Cortex",
        "gear_class": "C",
        "cost": 430,
        "source": "chest",
        "description": "A neural net woven by hand from ancient schematics.",
        "stats": {"mem": 5, "foc": 2},
    },
    {
        "id": "strider_frame",
        "slot": "legs",
        "name": "Strider's Frame",
        "gear_class": "C",
        "cost": 440,
        "source": "chest",
        "description": "Every step feels like the first. Fatigue does not exist.",
        "stats": {"spd": 5, "pwr": 2},
    },
    {
        "id": "ring_of_embers",
        "slot": "ring1",
        "name": "Ring of Embers",
        "gear_class": "C",
        "cost": 380,
        "source": "chest",
        "description": "The warmth persists even in the coldest places.",
        "stats": {"lck": 3, "spd": 2, "foc": 2},
    },
    {
        "id": "severance_clasp",
        "slot": "offhand",
        "name": "Severance Clasp",
        "gear_class": "C",
        "cost": 410,
        "source": "chest",
        "description": "A clasp that severs unwanted connections.",
        "stats": {"def": 4, "mem": 2, "lck": 1},
    },
    {
        "id": "foxblood_ring",
        "slot": "ring2",
        "name": "Foxblood Ring",
        "gear_class": "C",
        "cost": 390,
        "source": "chest",
        "description": "Fox blood in resin. The owner is never the last to leave.",
        "stats": {"mem": 4, "lck": 3},
    },
    {
        "id": "crown_of_the_waning",
        "slot": "headware",
        "name": "Crown of the Waning",
        "gear_class": "B",
        "cost": 1200,
        "source": "chest",
        "description": "Worn by kings of fading kingdoms. The crown outlived them all.",
        "stats": {"foc": 6, "mem": 3, "lck": 2},
    },
    {
        "id": "the_unbroken",
        "slot": "core",
        "name": "The Unbroken",
        "gear_class": "B",
        "cost": 1400,
        "source": "chest",
        "description": "It has no name. Only a reputation.",
        "stats": {"def": 7, "pwr": 3},
    },
    {
        "id": "hollow_eye_link",
        "slot": "neural_link",
        "name": "Hollow Eye Link",
        "gear_class": "B",
        "cost": 1300,
        "source": "chest",
        "description": "Looks inward, not outward.",
        "stats": {"mem": 6, "spd": 3, "lck": 2},
    },
    {
        "id": "gravewarden_legs",
        "slot": "legs",
        "name": "Gravewarden Legs",
        "gear_class": "B",
        "cost": 1350,
        "source": "chest",
        "description": "Faster than thought. Faster than regret.",
        "stats": {"spd": 7, "lck": 3},
    },
    {
        "id": "seal_of_quiet_ruin",
        "slot": "ring1",
        "name": "Seal of Quiet Ruin",
        "gear_class": "B",
        "cost": 1100,
        "source": "chest",
        "description": "A quiet fall is the most terrible kind.",
        "stats": {"lck": 5, "spd": 3, "foc": 2},
    },
    {
        "id": "oracle_of_the_last_age",
        "slot": "headware",
        "name": "Oracle of the Last Age",
        "gear_class": "A",
        "cost": 0,
        "source": "chest",
        "description": "Sees the end of every line. Stays silent about it.",
        "stats": {"foc": 8, "mem": 4, "lck": 3},
    },
    {
        "id": "ebon_mantle",
        "slot": "core",
        "name": "Ebon Mantle",
        "gear_class": "A",
        "cost": 0,
        "source": "chest",
        "description": "A black cloak with no source. It casts no shadow.",
        "stats": {"def": 9, "pwr": 5},
    },
    {
        "id": "ring_of_the_first_fire",
        "slot": "ring2",
        "name": "Ring of the First Fire",
        "gear_class": "A",
        "cost": 0,
        "source": "chest",
        "description": "A fire that burned before the word 'fire' existed.",
        "stats": {"lck": 7, "spd": 4, "mem": 3},
    },
    {
        "id": "mask_of_the_nameless",
        "slot": "headware",
        "name": "Mask of the Nameless",
        "gear_class": "S",
        "cost": 0,
        "source": "chest",
        "description": "The name was erased. The mask remained.",
        "stats": {"foc": 10, "mem": 5, "lck": 3, "pwr": 2},
    },
    {
        "id": "gauntlet_of_the_epoch",
        "slot": "arms",
        "name": "Gauntlet of the Epoch",
        "gear_class": "S",
        "cost": 0,
        "source": "chest",
        "description": "You put it on once. It is not removed.",
        "stats": {"pwr": 10, "def": 5, "spd": 3},
    },
    {
        "id": "focus_stim",
        "slot": "consumable",
        "name": "Focus Stim",
        "description": "Grants +30% Focus multiplier for your next Focus Session.",
        "gear_class": None,
        "cost": 30,
    },
    {
        "id": "memory_patch",
        "slot": "consumable",
        "name": "Memory Patch",
        "description": "Instantly boosts your Growth Coefficient (Gc) by +0.2.",
        "gear_class": None,
        "cost": 35,
    },
    {
        "id": "xp_booster",
        "slot": "consumable",
        "name": "XP Booster",
        "description": "Grants +50% XP from all sources for 24 hours.",
        "gear_class": None,
        "cost": 80,
    },
    {
        "id": "streak_shield",
        "slot": "consumable",
        "name": "Streak Shield",
        "description": "Automatically protects your daily streak from breaking once if you miss a day.",
        "gear_class": None,
        "cost": 200,
    },
    {
        "id": "boss_damage_plus",
        "slot": "consumable",
        "name": "Boss Damage+",
        "description": "Deals +50% damage to the boss in your next Focus Session.",
        "gear_class": None,
        "cost": 60,
    },
    {
        "id": "small_heal",
        "slot": "consumable",
        "name": "Small Health Potion",
        "description": "Restores 20 HP instantly.",
        "gear_class": None,
        "cost": 25,
        "hp_boost": 20,
    },
    {
        "id": "medium_heal",
        "slot": "consumable",
        "name": "Health Potion",
        "description": "Restores 50 HP instantly.",
        "gear_class": None,
        "cost": 60,
        "hp_boost": 50,
    },
    {
        "id": "large_heal",
        "slot": "consumable",
        "name": "Mega Health Potion",
        "description": "Restores 100 HP instantly.",
        "gear_class": None,
        "cost": 150,
        "hp_boost": 100,
    },
    {
        "id": "elixir",
        "slot": "consumable",
        "name": "Elixir of Life",
        "description": "Restores HP to 100% and grants 10 minutes of complete damage immunity.",
        "gear_class": None,
        "cost": 500,
        "hp_boost": 9999,
    },
    {
        "id": "wanderers_hood",
        "slot": "headware",
        "name": "Wanderer's Hood",
        "gear_class": "C",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "misted_hood",
        "slot": "headware",
        "name": "Misted Wanderer's Hood",
        "gear_class": "C",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "bone_bracelet",
        "slot": "arms",
        "name": "Bone Bracelet",
        "gear_class": "C",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "heralds_fang",
        "slot": "core",
        "name": "Herald's Fang",
        "gear_class": "C",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "wardens_quill",
        "slot": "arms",
        "name": "Warden's Quill",
        "gear_class": "C",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "echo_bell",
        "slot": "ring1",
        "name": "Echo Bell",
        "gear_class": "B",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "frostbite_blade",
        "slot": "arms",
        "name": "Frostbite Blade",
        "gear_class": "B",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "silk_mantle",
        "slot": "core",
        "name": "Silk Mantle",
        "gear_class": "B",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "ember_gauntlet",
        "slot": "arms",
        "name": "Ember Gauntlet",
        "gear_class": "B",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "glass_tear",
        "slot": "ring2",
        "name": "Glass Tear",
        "gear_class": "B",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "leviathan_scale",
        "slot": "core",
        "name": "Leviathan Scale",
        "gear_class": "B",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "crown_of_ash",
        "slot": "headware",
        "name": "Crown of Ash",
        "gear_class": "A",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "golems_grip",
        "slot": "arms",
        "name": "Golem's Grip",
        "gear_class": "A",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "scar_shard",
        "slot": "core",
        "name": "Scar Shard",
        "gear_class": "A",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "forgotten_score",
        "slot": "neural_link",
        "name": "Forgotten Score",
        "gear_class": "A",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "abyssal_purse",
        "slot": "ring1",
        "name": "Abyssal Purse",
        "gear_class": "A",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "winter_plate",
        "slot": "core",
        "name": "Winter Plate",
        "gear_class": "A",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "throne_seal",
        "slot": "ring2",
        "name": "Throne Seal",
        "gear_class": "S",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "eclipse_eye",
        "slot": "neural_link",
        "name": "Eclipse Eye",
        "gear_class": "S",
        "cost": 0,
        "source": "boss_drop",
    },
    {
        "id": "blade_final_dusk",
        "slot": "arms",
        "name": "Blade of Final Dusk",
        "gear_class": "S",
        "cost": 0,
        "source": "boss_drop",
    },
    # ── SS RANK — Transcendent tier (Quantum Safe only, 0.11% chance) ──────────
    {
        "id": "quantum_cortex_ss",
        "slot": "headware",
        "name": "Quantum Cortex Mk.II",
        "gear_class": "SS",
        "cost": 0,
        "source": "chest",
        "description": "A neural processor that thinks in dimensions humans cannot perceive.",
        "stats": {"foc": 12, "mem": 8, "pwr": 5},
    },
    {
        "id": "void_link_ss",
        "slot": "neural_link",
        "name": "Void-Link Lattice",
        "gear_class": "SS",
        "cost": 0,
        "source": "chest",
        "description": "Connects the user directly to the substrate of reality.",
        "stats": {"mem": 15, "lck": 6, "foc": 4},
    },
    {
        "id": "aegis_core_ss",
        "slot": "core",
        "name": "Aegis Omni-Core",
        "gear_class": "SS",
        "cost": 0,
        "source": "chest",
        "description": "Omni-directional barrier weave. Absorbs damage from all known threat vectors.",
        "stats": {"def": 18, "pwr": 4},
        "hp_boost": 200,
    },
    {
        "id": "phantom_arms_ss",
        "slot": "arms",
        "name": "Phantom Gauntlets",
        "gear_class": "SS",
        "cost": 0,
        "source": "chest",
        "description": "Strike before the target registers your intent.",
        "stats": {"pwr": 14, "def": 8, "lck": 4},
    },
    {
        "id": "gravshift_legs_ss",
        "slot": "legs",
        "name": "Gravshift Striders",
        "gear_class": "SS",
        "cost": 0,
        "source": "chest",
        "description": "Repurpose gravity. Walk walls. Ignore falling damage entirely.",
        "stats": {"def": 10, "pwr": 8, "foc": 6},
    },
    {
        "id": "sovereign_ring_ss",
        "slot": "ring1",
        "name": "Sovereign Signet",
        "gear_class": "SS",
        "cost": 0,
        "source": "chest",
        "description": "Worn by operators who bend the economy of war to their will.",
        "stats": {"lck": 10, "xp_boost": 15, "gold_boost": 10},
    },
    {
        "id": "eclipse_charm_ss",
        "slot": "charm",
        "name": "Eclipse Talisman",
        "gear_class": "SS",
        "cost": 0,
        "source": "chest",
        "description": "Carries the light of a dead star. Immense gravitational focus.",
        "stats": {"foc": 10, "pwr": 6, "lck": 8},
    },
    {
        "id": "neural_mantle_ss",
        "slot": "core",
        "name": "Neural Mantle X",
        "gear_class": "SS",
        "cost": 0,
        "source": "chest",
        "description": "Wraps the cortex in a mana-conductive lattice of pure signal.",
        "stats": {"mem": 12, "foc": 8},
        "hp_boost": 80,
    },
    {
        "id": "warpstep_ss",
        "slot": "legs",
        "name": "Warpstep Boots",
        "gear_class": "SS",
        "cost": 0,
        "source": "chest",
        "description": "Each step lands a microsecond before the previous one.",
        "stats": {"pwr": 10, "lck": 10, "def": 5},
    },
    {
        "id": "cipher_ring_ss",
        "slot": "ring2",
        "name": "Cipher Loop",
        "gear_class": "SS",
        "cost": 0,
        "source": "chest",
        "description": "Encodes your presence so the market favors you unconsciously.",
        "stats": {"gold_boost": 20, "lck": 8, "mem": 5},
    },
    # ── SSS RANK — Singularity tier (Quantum Safe only, 0.01% chance) ─────────
    {
        "id": "omnimind_crown_sss",
        "slot": "headware",
        "name": "Omnimind Crown",
        "gear_class": "SSS",
        "cost": 0,
        "source": "chest",
        "description": "The last prototype before the AI singularity shut down the lab.",
        "stats": {"foc": 25, "mem": 20, "pwr": 15},
    },
    {
        "id": "singularity_link_sss",
        "slot": "neural_link",
        "name": "Singularity Node",
        "gear_class": "SSS",
        "cost": 0,
        "source": "chest",
        "description": "At this bandwidth, thought and action are the same thing.",
        "stats": {"mem": 30, "foc": 15, "lck": 12},
    },
    {
        "id": "titan_core_sss",
        "slot": "core",
        "name": "Titan Omni-Shell",
        "gear_class": "SSS",
        "cost": 0,
        "source": "chest",
        "description": "Classified. Made from materials that don't exist in this dimension.",
        "stats": {"def": 35, "pwr": 10},
        "hp_boost": 500,
    },
    {
        "id": "void_fist_sss",
        "slot": "arms",
        "name": "Void Annihilator",
        "gear_class": "SSS",
        "cost": 0,
        "source": "chest",
        "description": "Contact with this gauntlet erases matter. Handle with extreme caution.",
        "stats": {"pwr": 30, "def": 15, "lck": 10},
    },
    {
        "id": "paradox_step_sss",
        "slot": "legs",
        "name": "Paradox Walkers",
        "gear_class": "SSS",
        "cost": 0,
        "source": "chest",
        "description": "Move through space before you decide to. Causality is optional.",
        "stats": {"def": 20, "pwr": 18, "lck": 15},
    },
    {
        "id": "infinity_sigil_sss",
        "slot": "ring1",
        "name": "Infinity Sigil",
        "gear_class": "SSS",
        "cost": 0,
        "source": "chest",
        "description": "Loops experience and gold back into itself. Compound gains are not metaphorical.",
        "stats": {"lck": 20, "xp_boost": 30, "gold_boost": 25},
    },
    {
        "id": "celestial_seal_sss",
        "slot": "charm",
        "name": "Celestial Seal",
        "gear_class": "SSS",
        "cost": 0,
        "source": "chest",
        "description": "Stamped by a civilization that ascended before recorded history.",
        "stats": {"foc": 20, "pwr": 15, "lck": 20},
    },
    {
        "id": "godcore_sss",
        "slot": "core",
        "name": "God-Core Protocol",
        "gear_class": "SSS",
        "cost": 0,
        "source": "chest",
        "description": "The last firmware update. The system never needed another.",
        "stats": {"mem": 25, "foc": 20, "damage_boost": 20},
        "hp_boost": 200,
    },
    {
        "id": "lightspeed_sss",
        "slot": "legs",
        "name": "Lightspeed Frame",
        "gear_class": "SSS",
        "cost": 0,
        "source": "chest",
        "description": "Travels faster than light. The legal implications are irrelevant.",
        "stats": {"pwr": 22, "lck": 18, "def": 12},
    },
    {
        "id": "ouroboros_sss",
        "slot": "ring2",
        "name": "Ouroboros Band",
        "gear_class": "SSS",
        "cost": 0,
        "source": "chest",
        "description": "Gold and experience feed each other endlessly. Wealth becomes inevitable.",
        "stats": {"gold_boost": 40, "xp_boost": 35, "lck": 15},
    },
]

print("Seeding items...")
for data in items_data:
    icon_path = f"/static/items/{data['id']}.webp"
    is_consumable = data["slot"] == "consumable"
    item_type = Item.ItemType.CONSUMABLE if is_consumable else Item.ItemType.EQUIPMENT
    slot_type = None if is_consumable else data["slot"]
    is_purchasable = data.get("source", "shop") == "shop"
    item, created = Item.objects.get_or_create(
        code=data["id"],
        defaults={
            "name": data["name"],
            "description": data.get("description", data["name"]),
            "item_type": item_type,
            "slot_type": slot_type,
            "icon_url": icon_path,
            "cost": data["cost"],
            "hp_boost": data.get("hp_boost", 0),
            "is_purchasable": is_purchasable,
            "source": data.get("source", "shop"),
            "gear_class": data.get("gear_class"),
        },
    )
    if not created:
        item.name = data["name"]
        item.description = data.get("description", data["name"])
        item.item_type = str(item_type)
        item.slot_type = str(slot_type) if slot_type else None
        item.icon_url = icon_path
        item.cost = int(data["cost"])
        item.hp_boost = int(data.get("hp_boost", 0))
        item.is_purchasable = bool(is_purchasable)
        item.source = data.get("source", "shop")
        item.gear_class = data.get("gear_class")
        item.save()
    item.effects.all().delete()
    for stat_name, stat_val in data.get("stats", {}).items():
        ItemEffect.objects.create(
            item=item, effect_name=stat_name, effect_value=float(stat_val)
        )
    status = "CREATED" if created else "UPDATED"
    gc = (
        f"[{data.get('gear_class', '-')}]" if data.get("gear_class") else "[consumable]"
    )
    print(f"  {status} {gc} {data['name']}")

print(f"\nSeeding complete! {len(items_data)} items processed.")

chests_data = [
    {
        "chest_type": "standard_cache",
        "name": "Standard Cache",
        "description": "A battered container of unknown origin. Common finds, rare surprises.",
        "cost_gold": 100,
        "drop_rates": {"E": 45, "D": 30, "C": 15, "B": 7, "A": 2.5, "S": 0.5},
        "icon_url": "/static/items/standard_cache.webp",
    },
    {
        "chest_type": "quantum_safe",
        "name": "Quantum Safe",
        "description": "Sealed with a lock that does not exist in three dimensions.",
        "cost_gold": 500,
        "drop_rates": {
            "E": 4.79,
            "D": 19.71,
            "C": 34.64,
            "B": 24.79,
            "A": 11.86,
            "S": 2.99,
            "SS": 0.11,
            "SSS": 0.01,
        },
        "icon_url": "/static/items/quantum_safe.webp",
    },
]
print("\nSeeding LootChests...")
for cd in chests_data:
    chest, created = LootChest.objects.get_or_create(
        chest_type=cd["chest_type"], defaults=cd
    )
    if not created:
        for k, v in cd.items():
            setattr(chest, k, v)
        chest.save()
    print(f"  {'CREATED' if created else 'UPDATED'} {cd['name']} ({cd['cost_gold']}g)")
print("\nAll done!")
