# Generated by Django 5.1.4 on 2026-08-27 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extensiontoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='extensiontoken',
            name='device_name',
            field=models.CharField(default='Browser Extension', max_length=100),
        ),
        migrations.AlterField(
            model_name='blockedsite',
            name='unlock_cost',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='extensiontoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
