export const QUOTES = [
  { text: "I can do all things through Christ which strengtheneth me.", ref: "Philippians 4:13" },
  { text: "Be strong and of a good courage; be not afraid.", ref: "Joshua 1:9" },
  { text: "The Lord is my shepherd; I shall not want.", ref: "Psalm 23:1" },
  { text: "Trust in the Lord with all thine heart.", ref: "Proverbs 3:5" },
  { text: "For I know the thoughts that I think toward you... to give you an expected end.", ref: "Jeremiah 29:11" },
  { text: "They that wait upon the Lord shall renew their strength.", ref: "Isaiah 40:31" },
  { text: "God is our refuge and strength, a very present help in trouble.", ref: "Psalm 46:1" },
  { text: "In all thy ways acknowledge him, and he shall direct thy paths.", ref: "Proverbs 3:6" },
  { text: "Let us not be weary in well doing.", ref: "Galatians 6:9" },
  { text: "The joy of the Lord is your strength.", ref: "Nehemiah 8:10" },
  { text: "Fear thou not; for I am with thee.", ref: "Isaiah 41:10" },
  { text: "Be not afraid, only believe.", ref: "Mark 5:36" },
  { text: "This is the day which the Lord hath made.", ref: "Psalm 118:24" },
  { text: "Delight thyself also in the Lord.", ref: "Psalm 37:4" },
  { text: "Cast thy burden upon the Lord, and he shall sustain thee.", ref: "Psalm 55:22" },
  { text: "The Lord is my light and my salvation; whom shall I fear?", ref: "Psalm 27:1" },
  { text: "Rejoice in the Lord alway.", ref: "Philippians 4:4" },
  { text: "Ask, and it shall be given you.", ref: "Matthew 7:7" },
  { text: "Be still, and know that I am God.", ref: "Psalm 46:10" },
  { text: "Great is thy faithfulness.", ref: "Lamentations 3:23" },
  { text: "The Lord will fight for you, and ye shall hold your peace.", ref: "Exodus 14:14" },
  { text: "With God all things are possible.", ref: "Matthew 19:26" },
  { text: "Commit thy way unto the Lord; trust also in him.", ref: "Psalm 37:5" },
  { text: "Weeping may endure for a night, but joy cometh in the morning.", ref: "Psalm 30:5" },
  { text: "Let not your heart be troubled.", ref: "John 14:1" },
  { text: "I will never leave thee, nor forsake thee.", ref: "Hebrews 13:5" },
  { text: "Be of good cheer; I have overcome the world.", ref: "John 16:33" },
  { text: "The steadfast of mind thou keepest in perfect peace.", ref: "Isaiah 26:3" },
  { text: "As thy days, so shall thy strength be.", ref: "Deuteronomy 33:25" },
  { text: "Whatsoever things are true... think on these things.", ref: "Philippians 4:8" },
  { text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", ref: "2 Timothy 1:7" },
  { text: "If God be for us, who can be against us?", ref: "Romans 8:31" },
  { text: "Fight the good fight of faith.", ref: "1 Timothy 6:12" },
  { text: "I have fought a good fight, I have finished my course.", ref: "2 Timothy 4:7" },
  { text: "Blessed are they that mourn: for they shall be comforted.", ref: "Matthew 5:4" },
  { text: "Draw nigh to God, and he will draw nigh to you.", ref: "James 4:8" },
  { text: "The name of the Lord is a strong tower.", ref: "Proverbs 18:10" },
  { text: "Wait on the Lord: be of good courage.", ref: "Psalm 27:14" },
  { text: "My grace is sufficient for thee.", ref: "2 Corinthians 12:9" },
  { text: "In quietness and in confidence shall be your strength.", ref: "Isaiah 30:15" },
  { text: "The Lord is nigh unto them that are of a broken heart.", ref: "Psalm 34:18" },
  { text: "Every good gift... is from above.", ref: "James 1:17" },
  { text: "Give thanks in every thing.", ref: "1 Thessalonians 5:18" },
  { text: "Blessed is the man that trusteth in the Lord.", ref: "Jeremiah 17:7" },
  { text: "Ye are the light of the world.", ref: "Matthew 5:14" },
  { text: "Faith is the substance of things hoped for.", ref: "Hebrews 11:1" },
  { text: "The righteous shall flourish like the palm tree.", ref: "Psalm 92:12" },
  { text: "Whoso trusteth in the Lord, happy is he.", ref: "Proverbs 16:20" },
  { text: "Behold, I make all things new.", ref: "Revelation 21:5" },
  { text: "The Lord thy God is with thee whithersoever thou goest.", ref: "Joshua 1:9" },
  { text: "Let your light so shine before men.", ref: "Matthew 5:16" },
  { text: "Blessed are the pure in heart: for they shall see God.", ref: "Matthew 5:8" },
  { text: "The Lord is good, a strong hold in the day of trouble.", ref: "Nahum 1:7" },
  { text: "It is God which worketh in you both to will and to do.", ref: "Philippians 2:13" },
  { text: "I press toward the mark for the prize.", ref: "Philippians 3:14" },
  { text: "The entrance of thy words giveth light.", ref: "Psalm 119:130" },
  { text: "Blessed be the God... who comforteth us in all our tribulation.", ref: "2 Corinthians 1:3-4" },
  { text: "Perfect love casteth out fear.", ref: "1 John 4:18" },
  { text: "The Lord upholdeth all that fall.", ref: "Psalm 145:14" },
  { text: "Ye shall know the truth, and the truth shall make you free.", ref: "John 8:32" },
  { text: "There hath no temptation taken you but such as is common to man.", ref: "1 Corinthians 10:13" },
  { text: "Be ye kind one to another, tenderhearted.", ref: "Ephesians 4:32" },
  { text: "The Lord is good unto them that wait for him.", ref: "Lamentations 3:25" },
  { text: "Now abideth faith, hope, charity, these three.", ref: "1 Corinthians 13:13" },
  { text: "As for God, his way is perfect.", ref: "Psalm 18:30" },
  { text: "He healeth the broken in heart.", ref: "Psalm 147:3" },
  { text: "Let all that you do be done in love.", ref: "1 Corinthians 16:14" },
  { text: "The Lord is my rock, and my fortress.", ref: "Psalm 18:2" },
  { text: "Blessed are the peacemakers.", ref: "Matthew 5:9" },
  { text: "Whatsoever ye do, do it heartily, as to the Lord.", ref: "Colossians 3:23" },
  { text: "Casting all your care upon him; for he careth for you.", ref: "1 Peter 5:7" },
  { text: "Rejoice evermore. Pray without ceasing.", ref: "1 Thessalonians 5:16-17" },
  { text: "God is not the author of confusion, but of peace.", ref: "1 Corinthians 14:33" },
  { text: "Thou wilt shew me the path of life.", ref: "Psalm 16:11" },
  { text: "Beloved, let us love one another.", ref: "1 John 4:7" },
  { text: "Blessed is he that trusteth in the Lord.", ref: "Proverbs 16:20" },
  { text: "The Lord will perfect that which concerneth me.", ref: "Psalm 138:8" },
  { text: "Ye have not, because ye ask not.", ref: "James 4:2" },
  { text: "Let brotherly love continue.", ref: "Hebrews 13:1" },
  { text: "A merry heart doeth good like a medicine.", ref: "Proverbs 17:22" },
  { text: "I will strengthen thee; yea, I will help thee.", ref: "Isaiah 41:10" },
  { text: "Godliness with contentment is great gain.", ref: "1 Timothy 6:6" },
  { text: "The Lord shall preserve thy going out and thy coming in.", ref: "Psalm 121:8" },
  { text: "Blessed is the man that walketh not in the counsel of the ungodly.", ref: "Psalm 1:1" },
  { text: "Charity suffereth long, and is kind.", ref: "1 Corinthians 13:4" },
  { text: "It is more blessed to give than to receive.", ref: "Acts 20:35" },
  { text: "God is love.", ref: "1 John 4:8" },
  { text: "Man doth not live by bread only.", ref: "Deuteronomy 8:3" },
  { text: "Come unto me, all ye that labour and are heavy laden.", ref: "Matthew 11:28" },
  { text: "The Lord bless thee, and keep thee.", ref: "Numbers 6:24" },
  { text: "Search me, O God, and know my heart.", ref: "Psalm 139:23" },
  { text: "Whom shall I fear? the Lord is the strength of my life.", ref: "Psalm 27:1" },
  { text: "Be sober, be vigilant.", ref: "1 Peter 5:8" },
  { text: "Faithful is he that calleth you, who also will do it.", ref: "1 Thessalonians 5:24" },
  { text: "Let your moderation be known unto all men.", ref: "Philippians 4:5" },
  { text: "The fruit of the Spirit is love, joy, peace.", ref: "Galatians 5:22" },
  { text: "Now unto him that is able to do exceeding abundantly.", ref: "Ephesians 3:20" },
  { text: "Whatsoever a man soweth, that shall he also reap.", ref: "Galatians 6:7" },
  { text: "Praise ye the Lord, for he is good.", ref: "Psalm 106:1" },
  { text: "The grace of our Lord Jesus Christ be with you all.", ref: "Revelation 22:21" }
];
